import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{createClient}from'@supabase/supabase-js';
import{Film,Clapperboard,Sparkles,Users,FolderKanban,Settings,UserCircle,Shield,Plus,Play,Save,Menu,X,ChevronRight,CheckCircle2,Clock3,Layers3,Wand2,LogOut,MapPin,Bot,Handshake,Bell,CreditCard,Eye,MessageSquare,KeyRound,Check, XCircle,Upload,Send,BookOpen,Info,Mail,Lock,Palette,Globe,Volume2}from'lucide-react';
import'./styles.css';
import Professional3DPreview from'./engine3d/Professional3DPreview';
import{postStudioJob}from'./services/studioApi';

const URL=import.meta.env.VITE_SUPABASE_URL||localStorage.getItem('VITE_SUPABASE_URL')||'';
const KEY=import.meta.env.VITE_SUPABASE_ANON_KEY||localStorage.getItem('VITE_SUPABASE_ANON_KEY')||'';
const sb=URL&&KEY?createClient(URL,KEY):null;
const ADMIN='ashurovabdulqodir10@gmail.com';
const PAYMENT_CARD='9860 0803 9422 9159';
const PAYMENT_NAME='Mamadaliyeva Sanamhon';
const uid=()=>crypto.randomUUID();
const UI_TEXT:any={
  uz:{home:'Bosh sahifa',create:'Kino yaratish',projects:'Loyihalar',integrations:'API ulash',collab:'Hamkorlik',partners:'Hamkorlar / Reklama',profile:'Profil',settings:'Sozlamalar',login:'Kirish',signup:'Ro‘yxatdan o‘tish',logout:'Chiqish',menu:'MENU',online:'AKKAUNT ONLINE',needLogin:'Yaratish uchun akkaunt kerak',account:'AKKAUNT',settingsTitle:'Sozlamalar',profileManage:'Profilni boshqarish',language:'Til',notifications:'Bildirishnomalar',notificationsOn:'Bildirishnomalarni yoqish',appearance:'Ko‘rinish',light:'Yorug‘',dark:'Qorong‘i',system:'Tizim',security:'Xavfsizlik',securityText:'Server maxfiy kalitlari foydalanuvchi interfeysida ko‘rsatilmaydi.',securityManage:'Xavfsizlikni boshqarish',aiVoice:'AI ovozi',aiVoiceText:'AI javoblari va kino dialoglari uchun ovoz profilini tanlang.',neutral:'Oddiy',warm:'Iliq',cinematic:'Kinematik',accountSection:'Akkaunt',save:'Saqlash',cancel:'Bekor qilish',currentPassword:'Joriy parol',newPassword:'Yangi parol',changePassword:'Parolni o‘zgartirish',passwordChanged:'Parol yangilandi.',wrongPassword:'Joriy parol noto‘g‘ri.',passwordLength:'Yangi parol kamida 6 belgidan iborat bo‘lsin.'},
  en:{home:'Home',create:'Create Movie',projects:'Projects',integrations:'API Connect',collab:'Collaboration',partners:'Partners / Ads',profile:'Profile',settings:'Settings',login:'Log in',signup:'Sign up',logout:'Log out',menu:'MENU',online:'ACCOUNT ONLINE',needLogin:'Account required to create',account:'ACCOUNT',settingsTitle:'Settings',profileManage:'Manage profile',language:'Language',notifications:'Notifications',notificationsOn:'Enable notifications',appearance:'Appearance',light:'Light',dark:'Dark',system:'System',security:'Security',securityText:'Server secret keys are never shown in the user interface.',securityManage:'Security settings',aiVoice:'AI voice',aiVoiceText:'Choose the voice profile for AI replies and movie dialogue.',neutral:'Neutral',warm:'Warm',cinematic:'Cinematic',accountSection:'Account',save:'Save',cancel:'Cancel',currentPassword:'Current password',newPassword:'New password',changePassword:'Change password',passwordChanged:'Password updated.',wrongPassword:'Current password is incorrect.',passwordLength:'New password must be at least 6 characters.'},
  ru:{home:'Главная',create:'Создать кино',projects:'Проекты',integrations:'API подключение',collab:'Сотрудничество',partners:'Партнёры / Реклама',profile:'Профиль',settings:'Настройки',login:'Войти',signup:'Регистрация',logout:'Выйти',menu:'МЕНЮ',online:'АККАУНТ ONLINE',needLogin:'Для создания нужен аккаунт',account:'АККАУНТ',settingsTitle:'Настройки',profileManage:'Управление профилем',language:'Язык',notifications:'Уведомления',notificationsOn:'Включить уведомления',appearance:'Вид',light:'Светлая',dark:'Тёмная',system:'Система',security:'Безопасность',securityText:'Секретные серверные ключи не отображаются в интерфейсе пользователя.',securityManage:'Настройки безопасности',aiVoice:'Голос AI',aiVoiceText:'Выберите голосовой профиль для ответов AI и диалогов фильма.',neutral:'Нейтральный',warm:'Тёплый',cinematic:'Кинематографичный',accountSection:'Аккаунт',save:'Сохранить',cancel:'Отмена',currentPassword:'Текущий пароль',newPassword:'Новый пароль',changePassword:'Изменить пароль',passwordChanged:'Пароль обновлён.',wrongPassword:'Текущий пароль неверен.',passwordLength:'Новый пароль должен содержать минимум 6 символов.'}
};
const getLang=()=>read('kino_settings',{language:'uz'}).language||'uz';
const T=(key:string,lang=getLang())=>UI_TEXT[lang]?.[key]??UI_TEXT.uz[key]??key;
const read=(k:string,d:any)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
const write=(k:string,v:any)=>localStorage.setItem(k,JSON.stringify(v));

type Character={id:string;name:string;role:string;height:number;skin:string;hair:string;cloth:string;accent:string;face:string;voice:string;gender:string;age:number;notes:string};
type Shot={id:string;title:string;duration:number;camera:string;lighting:string;environment:string;action:string;dialogue:string;emotion:string;characterIds:string[];locationId?:string};
type Location={id:string;name:string;type:string;description:string;public:boolean};
type Project={id:string;title:string;style:string;status:string;script:string;characters:Character[];locations:Location[];shots:Shot[];createdAt:string;ownerName?:string;ownerEmail?:string;public?:boolean;videoUrl?:string};
type Rule={id:string;text:string;active:boolean;createdAt:string};
type Payment={id:string;email:string;kind:'advertising'|'collaboration';amount:string;status:'pending'|'approved'|'rejected';receiptName:string;createdAt:string;note?:string};

const newChar=(name='Sardor'):Character=>({id:uid(),name,role:'Bosh qahramon',height:1.72,skin:'#b97852',hair:'#17191f',cloth:'#26334b',accent:'#d98d4d',face:'natural',voice:(read('kino_settings',{aiVoice:'neutral'}).aiVoice||'neutral'),gender:'male',age:25,notes:''});
const starter=():Project=>{const c=newChar();const l={id:uid(),name:'Asosiy lokatsiya',type:'cinematic',description:'Ssenariy asosida yaratiladigan muhit.',public:false};return{id:uid(),title:'Yangi kino',style:'Photorealistic Cinematic',status:'draft',script:'',characters:[c],locations:[l],shots:[],createdAt:new Date().toISOString(),public:false}};

function analyzeScript(text:string,p:Project){
 const clean=text.trim(); if(!clean)return p;
 const sentences=clean.split(/(?<=[.!?])\s+/).filter(Boolean);
 const chars=p.characters.length?p.characters:[newChar()];
 const loc=p.locations[0]||{id:uid(),name:'Asosiy lokatsiya',type:'cinematic',description:'',public:false};
 const shots=sentences.slice(0,30).map((s,i)=>({id:uid(),title:`${String(i+1).padStart(2,'0')} — ${s.slice(0,50)}`,duration:Math.max(3,Math.min(20,Math.round(4+s.length/45))),camera:['24mm · wide · dolly','50mm · medium · tracking','85mm · close-up · orbit'][i%3],lighting:'Key + fill + rim · volumetric',environment:loc.name,action:s,dialogue:'',emotion:['neutral','curious','tense','hopeful'][i%4],characterIds:chars.map(c=>c.id),locationId:loc.id}));
 return {...p,script:clean,status:'analyzed',shots};
}

function App(){
 const[page,setPage]=useState('home'),[open,setOpen]=useState(false),[session,setSession]=useState<any>(null),[project,setProject]=useState<Project>(()=>read('kino_active_project',starter())),[projects,setProjects]=useState<Project[]>([]),[script,setScript]=useState(''),[saved,setSaved]=useState(false),[authMode,setAuthMode]=useState<'login'|'signup'>('login'),[email,setEmail]=useState(''),[pass,setPass]=useState(''),[fullName,setFullName]=useState(''),[avatar,setAvatar]=useState(''),[verifyCode,setVerifyCode]=useState(''),[msg,setMsg]=useState(''),[isAdmin,setIsAdmin]=useState(false),[rules,setRules]=useState<Rule[]>(()=>read('kino_rules',[])),[config,setConfig]=useState<any>(()=>read('kino_config',{})),[theme,setTheme]=useState(()=>read('kino_settings',{language:'uz',notifications:true,theme:'light'}).theme||'light'),[language,setLanguage]=useState(()=>getLang());
 useEffect(()=>{const local=localStorage.getItem('kino_session');if(local)setSession(JSON.parse(local));if(sb){sb.auth.getSession().then(({data})=>data.session&&setSession(data.session));const sub=sb.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>sub.data.subscription.unsubscribe()}},[]);
 useEffect(()=>{const prefs=read('kino_settings',{theme:'light',language:'uz'});const t=prefs.theme==='system'?(window.matchMedia?.('(prefers-color-scheme: dark)').matches?'dark':'light'):prefs.theme||'light';setTheme(t);setLanguage(prefs.language||'uz');document.documentElement.dataset.theme=t;document.documentElement.lang=prefs.language||'uz';
   const onSettings=(e:any)=>{const d=e.detail||{};if(d.language){setLanguage(d.language);document.documentElement.lang=d.language;}if(d.theme){setTheme(d.theme);document.documentElement.dataset.theme=d.theme;}if(d.aiVoice){setProject((prev:any)=>({...prev,characters:(prev.characters||[]).map((c:any)=>({...c,voice:d.aiVoice}))}));}};
   window.addEventListener('kino-settings-change',onSettings);return()=>window.removeEventListener('kino-settings-change',onSettings);
 },[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;},[theme]);
 useEffect(()=>{if(project?.id)write('kino_active_project',project);},[project]);
 useEffect(()=>{if(session){setIsAdmin((session.user?.email||session.email||'').toLowerCase()===ADMIN||!!session.isAdmin);loadProjects();(async()=>{if(sb&&session.user?.id){const{data}=await sb.from('studio_profiles').select('*').eq('studio_user_id',session.user.id).maybeSingle();if(data){setFullName(data.studio_full_name||'');setAvatar(data.studio_avatar_data||'');setSession((x:any)=>x?{...x,user:{...x.user,user_metadata:{...(x.user?.user_metadata||{}),full_name:data.studio_full_name,avatar_url:data.studio_avatar_data}}}:x)}}})()}},[session?.user?.id]);
 useEffect(()=>{const protectedPages=['create','projects','integrations','collab','partners','settings'];if(protectedPages.includes(page)&&!session)setPage('home')},[page,session]);
 async function loadProjects(){if(!sb||!session?.user?.id){setProjects(read('kino_local_projects',[]));return}const{data}=await sb.from('studio_projects').select('*').eq('studio_owner_id',session.user.id).order('studio_created_at',{ascending:false});const base=(data||[]).map((p:any)=>({...starter(),id:p.studio_project_id,title:p.studio_name,status:p.studio_status,script:p.studio_description||'',createdAt:p.studio_created_at,ownerName:p.studio_owner_name,ownerEmail:p.studio_owner_email,public:p.studio_public}));const{data:ctx}=await sb.from('studio_project_context').select('studio_project_id,studio_context').eq('studio_user_id',session.user.id);const byId:any={};(ctx||[]).forEach((x:any)=>{if(x.studio_context?.project)byId[x.studio_project_id]=x.studio_context.project});setProjects(base.map((p:any)=>byId[p.id]?{...p,...byId[p.id]}:p));}
 async function save(){const u=session?.user||session;const item={...project,script,ownerName:u?.user_metadata?.full_name||u?.name||u?.email,ownerEmail:u?.email};const arr=read('kino_local_projects',[]);write('kino_local_projects',[item,...arr.filter((x:any)=>x.id!==item.id)]);setProjects([item,...arr.filter((x:any)=>x.id!==item.id)]);if(sb&&u?.id){await sb.from('studio_projects').upsert({studio_project_id:item.id,studio_owner_id:u.id,studio_name:item.title,studio_description:item.script,studio_status:item.status,studio_created_at:item.createdAt,studio_updated_at:new Date().toISOString(),studio_public:item.public??false,studio_owner_name:item.ownerName,studio_owner_email:item.ownerEmail});await sb.from('studio_project_context').upsert({studio_project_id:item.id,studio_user_id:u.id,studio_script:item.script,studio_context:{project:item},studio_updated_at:new Date().toISOString()});}setSaved(true);setTimeout(()=>setSaved(false),1200)}
 async function auth(){
   if(!email||pass.length<6){setMsg('Email va kamida 6 belgili parol kiriting.');return}
   if(authMode==='signup' && !fullName.trim()){setMsg('Avval ismingizni kiriting.');return}
   if(sb){
     if(authMode==='signup'){
       const r=await sb.auth.signUp({email,password:pass,options:{data:{full_name:fullName.trim()}}});
       if(r.error){setMsg(r.error.message);return}
       if(r.data.user){
         if(avatar) await sb.from('studio_profiles').upsert({studio_user_id:r.data.user.id,studio_full_name:fullName.trim(),studio_avatar_data:avatar,studio_email:email});
         else await sb.from('studio_profiles').upsert({studio_user_id:r.data.user.id,studio_full_name:fullName.trim(),studio_email:email});
       }
       if(r.data.session){setSession(r.data.session);setMsg('Akkaunt yaratildi.')}
       else setMsg('Email tasdiqlash kodi yuborildi. Emailingizni tasdiqlab, keyin kiring.');
     }else{
       const r=await sb.auth.signInWithPassword({email,password:pass});
       if(r.error){setMsg(r.error.message);return}
       setSession(r.data.session);
     }
     return;
   }
   const users=read('kino_local_users',[]);let u=users.find((x:any)=>x.email===email);
   if(authMode==='signup'){
     if(u){setMsg('Bu email allaqachon mavjud.');return}
     u={id:uid(),email,password:pass,name:fullName.trim(),avatar,isAdmin:email.toLowerCase()===ADMIN,verified:false};
     write('kino_local_users',[...users,u]);const code=String(Math.floor(100000+Math.random()*900000));write('kino_pending_verify',{email,code,name:fullName.trim(),avatar});setMsg(`Tasdiqlash kodi: ${code}`);return
   }else if(!u||u.password!==pass){setMsg('Email yoki parol noto‘g‘ri.');return}
   const sess={user:{id:u.id,email:u.email,user_metadata:{full_name:u.name,avatar_url:u.avatar}},email:u.email,isAdmin:u.isAdmin};
   write('kino_session',sess);setSession(sess);
 } 
 async function verifyEmail(){if(!verifyCode.trim()){setMsg('Emailga kelgan tasdiqlash kodini kiriting.');return false}if(!sb){const p=read('kino_pending_verify',null);if(!p||p.email!==email||p.code!==verifyCode.trim()){setMsg('Tasdiqlash kodi noto‘g‘ri.');return false}const users=read('kino_local_users',[]).map((u:any)=>u.email===email?{...u,verified:true,avatar}:u);write('kino_local_users',users);const u=users.find((x:any)=>x.email===email);const sess={user:{id:u.id,email:u.email,user_metadata:{full_name:u.name,avatar_url:u.avatar}},email:u.email,isAdmin:u.isAdmin};write('kino_session',sess);setSession(sess);localStorage.removeItem('kino_pending_verify');return true} const r=await sb.auth.verifyOtp({email,token:verifyCode.trim(),type:'signup'});if(r.error){setMsg(r.error.message);return false}setSession(r.data.session);if(r.data.user)await sb.from('studio_profiles').upsert({studio_user_id:r.data.user.id,studio_full_name:fullName.trim(),studio_email:email,studio_avatar_data:avatar||null});return true}
 function logout(){localStorage.removeItem('kino_session');sb?.auth.signOut();setSession(null);setIsAdmin(false);setPage('home')}
 const go=(n:string)=>{setPage(n);setOpen(false)};
 const nav:any[]=[['home',T('home',language),Clapperboard],['create',T('create',language),Film],['projects',T('projects',language),FolderKanban],['integrations',T('integrations',language),Bot],['collab',T('collab',language),Handshake],['partners',T('partners',language),CreditCard],['profile',T('profile',language),UserCircle],['settings',T('settings',language),Settings]];
 return <div className="app"><aside className={'side '+(open?'open':'')}><div className="brand"><div className="logo"><Film/></div><b>KINO AI<small>STUDIO</small></b><button className="icon mobileX" onClick={()=>setOpen(false)}><X/></button></div><div className="label">{T('menu',language)}</div>{nav.map(([n,t,I])=><button key={n} className={'nav '+(page===n?'sel':'')} onClick={()=>{if(n!=='home'&&!session){go('profile');setMsg('Bu bo‘lim uchun ro‘yxatdan o‘ting yoki tizimga kiring.')}else go(n)}}><I size={18}/><span>{t}</span>{page===n&&<ChevronRight size={14}/>}</button>)}<div className="bottom">{session?<button className="nav" onClick={logout}><LogOut size={18}/><span>{T('logout',language)}</span></button>:<div className="online">● KIRISH KERAK<small>{T('needLogin',language)}</small></div>}</div></aside><main><header><button className="icon menu" onClick={()=>setOpen(true)}><Menu/></button><span>KINO AI STUDIO / {nav.find(x=>x[0]===page)?.[1]||T('home',language)}</span><div>{session?<em>● {isAdmin?'ADMIN':'AKKAUNT'} ONLINE</em>:<><button className="ghost" onClick={()=>go('profile')}>{T('login',language)}</button><button className="primary sm" onClick={()=>{setAuthMode('signup');go('profile')}}>{T('signup',language)}</button></>}</div></header>
 {page==='home'&&<Home go={go} session={session}/>} 
 {page==='create'&&<Create project={project} setProject={setProject} script={script} setScript={setScript} save={save} saved={saved} config={config} setPage={go} session={session} isAdmin={isAdmin}/>} 
 {page==='projects'&&<Projects projects={projects} setProject={(p:any)=>{setProject(p);write('kino_active_project',p)}} go={go}/>} 
 
 {page==='integrations'&&<Integrations/>} {page==='collab'&&<Collab/>} {page==='partners'&&<Partners go={go}/>} {page==='profile'&&<Profile session={session} mode={authMode} setMode={setAuthMode} email={email} setEmail={setEmail} pass={pass} setPass={setPass} fullName={fullName} setFullName={setFullName} avatar={avatar} setAvatar={setAvatar} verifyCode={verifyCode} setVerifyCode={setVerifyCode} verifyEmail={verifyEmail} msg={msg} auth={auth} projects={projects} go={go}/>} {page==='settings'&&<SettingsPage session={session} logout={logout} setAuthMode={setAuthMode} go={go} language={language}/>}
 </main></div>
}

function Home({go,session}:any){return <div className="page"><section className="hero"><div className="heroText"><div className="eyebrow">KINO AI STUDIO</div><h1>G‘oyangizni<br/><span>kinoga aylantiring.</span></h1><p>AI ssenariyni tushunadi, uni kuchaytiradi, personaj va sahnalarni tahlil qiladi, keyin Kino AI Studio’ning o‘z 3D kino tizimiga uzatadi.</p>{session?<button className="primary" onClick={()=>go('create')}><Play size={17}/> Kino yaratishni boshlash</button>:<div className="row"><button className="primary" onClick={()=>go('profile')}><UserCircle size={17}/> Ro‘yxatdan o‘tish</button><button className="ghost" onClick={()=>go('profile')}><KeyRound size={17}/> Kirish</button></div>}</div><div className="reel"><Film size={64}/><b>AI<br/>CINEMA<br/>STUDIO</b></div></section><div className="head"><div><div className="eyebrow">NIMALAR QILA OLADI?</div><h2>Kino yaratish oddiy suhbatdan boshlanadi</h2></div></div><div className="cards"><div className="card"><Sparkles/><b>AI bilan ssenariy</b><p>G‘oyani yozing. AI uni kino ssenariysiga aylantiradi va siz bilan kino mavzusida suhbatlashadi.</p></div><div className="card"><Users/><b>Personajlar</b><p>Personajlar uchun reference rasm yuborish, identity va continuity saqlash.</p></div><div className="card"><Layers3/><b>Sahnalar va kadrlar</b><p>Ssenariy avtomatik sahna, shot, harakat, kamera va muhit rejasiga ajratiladi.</p></div><div className="card"><Film/><b>O‘z 3D kino tizimi</b><p>Tayyor video AI modeliga bog‘lanmasdan, o‘zimizning 3D/render qatlamimiz bilan ishlash.</p></div></div><section className="panel" style={{marginTop:16}}><div className="row"><Info/><div><b>AI chegarasi</b><p>Kino AI Studio AI’si kino yaratish va ilovaning o‘zidan foydalanish mavzusida yordam beradi. Boshqa mavzularga o‘tmaydi.</p></div></div></section></div>}

function Create({project,setProject,script,setScript,save,saved,config,setPage,session,isAdmin}:any){
 const[busy,setBusy]=useState(false),[chat,setChat]=useState<{role:string,text:string,id?:string}[]>(()=>read(`kino_chat_${project.id}`,[])),[composer,setComposer]=useState(''),[adminMode,setAdminMode]=useState(false);
 const[adFlow,setAdFlow]=useState(()=>localStorage.getItem('kino_reklama_flow')==='true'),[receipt,setReceipt]=useState<File|null>(null),[receiptSent,setReceiptSent]=useState(false);
 useEffect(()=>{const local=read(`kino_chat_${project.id}`,[]);setChat(local);(async()=>{if(sb&&session?.user?.id){const{data}=await sb.from('studio_chat_messages').select('*').eq('studio_owner_id',session.user.id).eq('studio_project_id',project.id).order('studio_created_at',{ascending:true});if(data?.length){const loaded=data.map((m:any)=>({id:m.studio_message_id,role:m.studio_role,text:m.studio_content||''}));setChat(loaded);write(`kino_chat_${project.id}`,loaded)}}})()},[session?.user?.id,project.id]);
 const persistChat=async(role:string,text:string)=>{const item={id:uid(),role,text};setChat(x=>{const next=[...x,item];write(`kino_chat_${project.id}`,next);return next});if(sb&&session?.user?.id)await sb.from('studio_chat_messages').insert({studio_message_id:item.id,studio_owner_id:session.user.id,studio_project_id:project.id,studio_role:role,studio_content:text})};
 const ask=async(text:string)=>{
   const clean=text.trim();if(!clean||busy)return;
   if(clean.toLowerCase()==='/admin'){if(isAdmin){setAdminMode(true);await persistChat('system','Admin rejimi ochildi. Qaysi qoida yoki AI xatti-harakatini o‘zgartirish kerakligini yozing. Tasdiqlanmaguncha hech narsa o‘zgarmaydi.')}else await persistChat('ai','Bu buyruq faqat administrator uchun mavjud.');return}
   await persistChat('user',clean);setComposer('');setBusy(true);
   try{
     const api=config.apiUrl||import.meta.env.VITE_STUDIO_API_URL||'';
     if(!api)throw new Error('AI_UNAVAILABLE');
     const history=[...chat,{role:'user',text:clean}].slice(-20);
     const rr=await fetch(api.replace(/\/$/,'')+'/ai/script',{method:'POST',headers:{'Content-Type':'application/json',...(config.clientKey?{'X-Client-Key':config.clientKey}:{})},body:JSON.stringify({userText:clean,history,project,rules:read('kino_rules',[])})});
     const rj=await rr.json();if(!rr.ok)throw new Error(rj?.error||'AI_UNAVAILABLE');
     const aiText=rj?.reply||rj?.choices?.[0]?.message?.content||'';
     if(!aiText)throw new Error('AI_UNAVAILABLE');
     await persistChat('ai',aiText);
     const looksLikeScript=/(ssenariy|sahna|shot|scene|dialog|kamera|personaj|qahramon|storyboard)/i.test(clean);
     if(looksLikeScript){
       const productionScript=[project.script?.trim(),clean].filter(Boolean).join('\n\n');
       const p=analyzeScript(productionScript,{...project,script:productionScript});
       setProject(p);setScript(productionScript);
     }
     if(sb&&session?.user?.id)await sb.from('studio_project_context').upsert({studio_project_id:project.id,studio_user_id:session.user.id,studio_script:project.script||'',studio_context:{project,chat:[...history,{role:'ai',text:aiText}]},studio_updated_at:new Date().toISOString()});
   }catch(e:any){
     const friendly=e.message==='AI_UNAVAILABLE'||e.message==='AI_TEMPORARILY_UNAVAILABLE'?'Hozircha AI javob bera olmayapti. Bir ozdan keyin yana urinib ko‘ring.':(e.message||'Hozircha javob berib bo‘lmadi.');
     await persistChat('ai',friendly);
   }finally{setBusy(false)}
 };
 const addRef=()=>persistChat('system','Reference rasmni yuboring — undan personaj ko‘rinishi va continuity uchun foydalanamiz.');
 const sendReceipt=async()=>{if(!receipt)return;const sess=read('kino_session',{});const item={id:uid(),email:sess?.user?.email||sess?.email||'noma’lum',kind:'advertising',amount:'reklama',status:'pending',receiptName:receipt.name,createdAt:new Date().toISOString()};const payments=read('kino_payments',[]);write('kino_payments',[item,...payments]);if(sb&&session?.user?.id)await sb.from('studio_ad_payment_requests').insert({id:item.id,studio_user_id:session.user.id,user_email:item.email,kind:item.kind,amount_text:item.amount,receipt_name:item.receiptName,status:'pending'});try{const api=config.apiUrl||'';if(api){const base64=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=reject;r.readAsDataURL(receipt)});await fetch(api.replace(/\/$/,'')+'/advertising/payment',{method:'POST',headers:{'Content-Type':'application/json','X-Client-Key':config.clientKey||''},body:JSON.stringify({...item,receiptBase64:base64})})}}catch{}setReceiptSent(true);await persistChat('ai','Reklama so‘rovingiz qabul qilindi.');setAdFlow(false);localStorage.removeItem('kino_reklama_flow')};
 return <div className="page aiCreatePage">
 {adminMode&&isAdmin&&<section className="panel adminRulePanel"><div className="head"><div><div className="eyebrow">ADMIN</div><h3>AI qoidasi / xatti-harakatini boshqarish</h3></div><button className="ghost" onClick={()=>setAdminMode(false)}>Yopish</button></div><p>Qaysi qoida yoki AI xatti-harakatini o‘zgartirish kerakligini yozing.</p><textarea value={composer} onChange={e=>setComposer(e.target.value)} placeholder="Masalan: Har bir sahnada personajning kiyimi va yuz identifikatsiyasi saqlansin."/><div className="row"><button className="primary" onClick={async()=>{const req=composer.trim();if(!req)return;const api=config.apiUrl||import.meta.env.VITE_STUDIO_API_URL||'';try{const r=await fetch(api.replace(/\/$/,'')+'/admin/command',{method:'POST',headers:{'Content-Type':'application/json',...(config.clientKey?{'X-Client-Key':config.clientKey}:{})},body:JSON.stringify({command:req,email:session?.user?.email||session?.email,chatId:session?.user?.id})});const j=await r.json();if(!r.ok)throw new Error('ADMIN_ERROR');const plan=j.plan||j;const rules=read('kino_rules',[]);write('kino_rules',[...rules,{...plan,text:req,active:false}]);await persistChat('system',`Admin qoida rejasi: ${plan.target||'all'} · ${plan.action||'require'}. Tasdiqlash talab qilinadi.`);setComposer('')}catch(e){await persistChat('system','Admin qoidasini yuborib bo‘lmadi.')}}}>Qoidani yuborish</button></div></section>}
 {adFlow&&<section className="panel"><div className="chatIntro"><CreditCard/><div><b>/reklama</b><p>Reklama so‘rovi uchun ma’lumot va chekni yuboring.</p></div></div><div className="row"><input type="file" accept="image/*,.pdf" onChange={e=>setReceipt((e.target as HTMLInputElement).files?.[0]||null)}/><button className="primary" disabled={!receipt} onClick={sendReceipt}><Upload/> So‘rovni yuborish</button></div>{receiptSent&&<div className="continuity">So‘rov qabul qilindi.</div>}</section>}
 <section className="kinoChatShell">
   <div className="kinoChatTop"><button className="chatMenuButton" onClick={()=>setPage('home')} aria-label="Orqaga"><ChevronRight className="backIcon"/></button><div className="kinoBrand"><span className="kinoBrandMark"><Film size={17}/></span><div><b>Kino AI</b><small>STUDIO</small></div></div><div className="kinoTopActions"><span className="kinoOnline">● ONLINE</span><button className="icon" onClick={save} title="Saqlash"><Save size={17}/></button></div></div>
   <div className="kinoChatLog">
     {chat.length===0&&<div className="kinoWelcome"><div className="kinoWelcomeIcon"><Sparkles size={20}/></div><h2>Salom! 🎬</h2><p>Bugun qanday kino yaratamiz? G‘oyangizni ayting — birga ssenariy, personajlar va sahnalarni ishlab chiqamiz.</p><div className="kinoQuick"><button onClick={()=>setComposer('Yangi kino g‘oyam bor, uni birga ssenariyga aylantiraylik.')}>G‘oyadan boshlash</button><button onClick={()=>setComposer('Menga kino uchun personaj va voqea tuzishda yordam ber.')}>Personaj yaratish</button></div></div>}
     {chat.map((m,i)=><div className={'kinoMessage '+m.role} key={m.id||i}>{m.role==='ai'&&<span className="kinoAvatar"><Sparkles size={13}/></span>}<div className="kinoMessageBody"><span className="kinoMessageName">{m.role==='ai'?'Kino AI':m.role==='user'?'Siz':'Studio'}</span><div className="kinoMessageText">{m.text}</div></div></div>)}
     {busy&&<div className="kinoMessage ai"><span className="kinoAvatar"><Sparkles size={13}/></span><div className="kinoTyping"><i></i><i></i><i></i></div></div>}
   </div>
   <div className="kinoComposerWrap"><div className="kinoComposer"><button className="composerPlus" onClick={addRef} aria-label="Reference"><Plus size={21}/></button><textarea value={composer} onChange={e=>setComposer(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask(composer)}}} placeholder="Kino haqida yozing..." rows={1}/><button className="composerSend" disabled={!composer.trim()||busy} onClick={()=>ask(composer)} aria-label="Yuborish"><Send size={17}/></button></div><small>AI Kino Studio bilan kino yaratish, ssenariy va sahnalar haqida suhbatlashing.</small></div>
 </section>
 <div className="grid kinoTools" style={{marginTop:14}}><section className="panel"><b>Personajlar</b>{project.characters.map(c=><div className="shot" key={c.id}><Users/><div><b>{c.name}</b><small>{c.role}</small></div><i>IDENTITY</i></div>)}<button className="ghost" onClick={()=>{const name=prompt('Personaj ismi');if(name)setProject((p:any)=>({...p,characters:[...p.characters,newChar(name)]}))}}><Plus/> Personaj qo‘shish</button></section><section className="panel"><b>Sahna va shotlar</b>{project.shots.length===0?<p>AI suhbat davomida kino tafsilotlari aniqlangach, sahnalar shu yerda paydo bo‘ladi.</p>:project.shots.map(s=><div className="shot" key={s.id}><span>{s.title.split(' ')[0]}</span><div><b>{s.title}</b><small>{s.camera} · {s.duration}s · {s.emotion}</small></div><i>READY</i></div>)}</section></div>
 </div>
}
function Projects({projects,setProject,go}:any){return <div className="page"><div className="head"><div><div className="eyebrow">PROJECTS</div><h2>Loyihalar</h2></div><button className="primary" onClick={()=>{setProject(starter());go('create')}}><Plus/> Yangi kino</button></div>{projects.length===0?<section className="panel"><b>Hali loyiha yo‘q.</b><p>Kino yaratishni boshlang.</p></section>:projects.map((p:any)=><section className="panel project" key={p.id}><div className="thumb"><Film/></div><div><b>{p.title}</b><p>{p.status} · {p.shots?.length||0} shot</p></div><button className="ghost" onClick={()=>{setProject(p);go('create')}}>Ochish</button></section>)}</div>}
function Integrations(){const[show,setShow]=useState(false);const[rule,setRule]=useState('');const[created,setCreated]=useState(()=>localStorage.getItem('kino_studio_api_key')||'');const createKey=async()=>{const k='kys_'+crypto.randomUUID().replaceAll('-','');setCreated(k);localStorage.setItem('kino_studio_api_key',k);setShow(false);if(sb){const u=(await sb.auth.getUser()).data.user;if(u)await sb.from('studio_api_keys').upsert({studio_user_id:u.id,studio_key:k,studio_label:'Default API key'})}};return <div className="page"><div className="head"><div><div className="eyebrow">DEVELOPER</div><h2>API ulash</h2></div></div><section className="panel apiGuide"><div className="apiIcon"><KeyRound/></div><h3>API kalit olishdan oldin qoidalar</h3><p>01 yoki 02 bo‘limini bosib tegishli API qoidalarini ko‘ring. Keyin haqiqiy kalit olish oynasini oching.</p><div className="apiSteps"><button onClick={()=>{setRule('01 — API kalit akkauntingizga bog‘lanadi. Uni faqat ishonchli server yoki Termux kabi xavfsiz joyda saqlang.')}}><b>01</b><span>API kalit qoidalari</span></button><button onClick={()=>{setRule('02 — Server maxfiy kalitlari oddiy foydalanuvchiga ko‘rsatilmaydi. API orqali yuborilgan foydalanuvchi/bot so‘rovlari siz belgilagan qoidalarga bo‘ysunadi.')}}><b>02</b><span>Xavfsizlik va foydalanish</span></button></div>{rule&&<div className="notice">{rule}</div>}<button className="primary" onClick={()=>setShow(true)}><KeyRound/> API kalit olish</button>{show&&<div className="apiModal"><div className="panel"><h3>API kalit yaratish</h3><p>Kalit shu akkaunt uchun yaratiladi. Uni xavfsiz joyga saqlang.</p><button className="primary" onClick={createKey}>Yangi kalit yaratish</button><button className="ghost" onClick={()=>setShow(false)}>Bekor qilish</button></div></div>}{created&&<div className="keyBox"><small>AKTIV API KALIT</small><code>{created}</code><button className="ghost" onClick={()=>navigator.clipboard?.writeText(created)}>Nusxalash</button></div>}</section></div>}
function Collab(){return <div className="page"><div className="head"><div><div className="eyebrow">COLLABORATION</div><h2>Hamkorlik</h2></div></div><section className="panel"><h3>Hamkorlik paketlari</h3><div className="planGrid"><button className="planCard" onClick={()=>alert('PRO hamkorlik qoidalari')}><b>PRO</b><span>Hamkorlik qoidalarini ko‘rish</span></button><button className="planCard" onClick={()=>alert('MAX hamkorlik qoidalari')}><b>MAX</b><span>Kengaytirilgan hamkorlik qoidalarini ko‘rish</span></button></div></section></div>}
function Partners({go}:any){
 const profiles=read('kino_partner_profiles',Array.from({length:12},(_,i)=>({id:i+1,name:['Nova Media','FrameLab','UzBrand','CinePro','Motion House','Pixel Art','Silk Road Media','Urban Ads','Vision Studio','Creative Hub','Media One','Kadr Agency'][i],avatar:`https://i.pravatar.cc/120?img=${i+10}`,views:1200+i*743,ads:4+i%7,joined:`2026-${String((i%9)+1).padStart(2,'0')}`})));
 const submit=()=>{write('kino_reklama_flow',true);go('create')};
 return <div className="page"><div className="head"><div><div className="eyebrow">BUSINESS</div><h2>Hamkorlar / Reklama</h2></div></div>
 <section className="panel"><h3>Hamkor profillari</h3><p>Har bir hamkorning profili va statistikasi alohida yuritiladi. Reklama to‘lovi tasdiqlangach, reklama beruvchining ma’lumotlari ham shu tizimga qo‘shiladi.</p><div className="partnerGrid">{profiles.map((x:any)=><article className="partnerCard" key={x.id}><img src={x.avatar} alt=""/><div><b>{x.name}</b><small>{x.ads} ta reklama · {x.views.toLocaleString()} ko‘rish</small><small>Hamkor: {x.joined}</small></div></article>)}</div><button className="primary" onClick={submit}><CreditCard/> Reklama berish</button></section></div>
}
function Profile({session,mode,setMode,email,setEmail,pass,setPass,msg,auth,projects,go,fullName,setFullName,avatar,setAvatar,verifyCode,setVerifyCode,verifyEmail}:any){
 const[stage,setStage]=useState(mode==='signup'?1:0);
 const pick=(e:any)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>setAvatar(String(r.result||''));r.readAsDataURL(f)};
 const submit=()=>{auth()};
 if(session)return <div className="page"><section className="profile profileHero">{session.user?.user_metadata?.avatar_url||session.avatar?<img src={session.user?.user_metadata?.avatar_url||session.avatar} className="profileAvatar"/>:<UserCircle size={54}/>}<div className="eyebrow">PROFILE</div><h2>{session.user?.user_metadata?.full_name||session.user?.email||session.email}</h2><p>{session.user?.email||session.email}</p></section><div className="stats"><div><b>{projects.length}</b><small>LOYIHALAR</small></div><div><b>{read('kino_saved_movies',[]).length}</b><small>SAQLANGAN</small></div><div><b>{projects.filter((p:any)=>p.status==='analyzed').length}</b><small>TAHLIL QILINGAN</small></div><div><b>AI</b><small>KINO STUDIO</small></div></div><section className="panel" style={{marginTop:14}}><h3>Mening loyihalarim</h3>{projects.map((p:any)=><div className="shot" key={p.id}><Film/><div><b>{p.title}</b><small>{p.status}</small></div><button className="ghost" onClick={()=>go('create')}><Eye/></button></div>)}</section></div>;
 return <div className="page authPage"><div className="authTitle"><div className="eyebrow">KINO AI STUDIO</div><h2>{mode==='login'?'Xush kelibsiz':'Professional akkaunt yarating'}</h2><p>{mode==='login'?'Akkauntingizga kiring.':'Ism, email va parol orqali akkaunt yarating; email tasdig‘idan so‘ng profil rasmini qo‘shing.'}</p></div><section className="panel authbox">{mode==='signup'&&<><div className="stepper"><span className={stage>=1?'on':''}>1 Ma’lumot</span><span className={stage>=2?'on':''}>2 Email</span><span className={stage>=3?'on':''}>3 Profil</span></div>{stage===1&&<><label>ISM</label><input value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="Ism va familiya"/><label>EMAIL</label><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@example.com"/><label>PAROL</label><input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="Kamida 6 belgi"/><button className="primary full" onClick={async()=>{if(fullName&&email&&pass.length>=6){await submit();setStage(2)}else setMsg('Ism, email va kamida 6 belgili parolni kiriting.')}}>Davom etish</button></>}{stage===2&&<><div className="verifyBox"><Mail/><h3>Emailni tasdiqlang</h3><p>Emailingizga kelgan tasdiqlash kodini kiriting.</p><input value={verifyCode} onChange={e=>setVerifyCode(e.target.value)} inputMode="numeric" placeholder="6 xonali kod"/></div><button className="primary full" onClick={async()=>{const ok=await verifyEmail();if(ok)setStage(3)}}>Emailni tasdiqlash</button></>}{stage===3&&<><label>PROFIL RASMI</label><input type="file" accept="image/*" onChange={pick}/>{avatar&&<img src={avatar} className="avatarPreview"/>}<p className="muted">Email tasdiqlangandan keyin profilingiz shu ism bilan ishlaydi.</p><button className="primary full" onClick={async()=>{if(sb&&session?.user?.id)await sb.from('studio_profiles').upsert({studio_user_id:session.user.id,studio_full_name:fullName.trim(),studio_email:email,studio_avatar_data:avatar||null});write('kino_profile',{name:fullName,email,avatar});go('create')}}>Profilni saqlash</button></>}{msg&&<div className="notice">{msg}</div>}</>}{mode==='login'&&<><label>EMAIL</label><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@example.com"/><label>PAROL</label><input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="••••••••"/><button className="primary full" onClick={submit}>Kirish</button>{msg&&<div className="notice">{msg}</div>}</>}<button className="text" onClick={()=>{setMode(mode==='login'?'signup':'login');setMsg('');setStage(1)}}>{mode==='login'?'Yangi akkaunt yaratish':'Akkauntim bor — kirish'}</button></section></div>
}
function SettingsPage({session,logout,setAuthMode,go,language}:any){
 const defaults={language:'uz',notifications:true,theme:'light',aiVoice:'neutral'};
 const[prefs,setPrefs]=useState(()=>read('kino_settings',defaults));
 const[securityOpen,setSecurityOpen]=useState(false),[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[notice,setNotice]=useState('');
 const tr=(k:string)=>T(k,prefs.language||language);
 const applyTheme=(v:string)=>{const t=v==='system'?(window.matchMedia?.('(prefers-color-scheme: dark)').matches?'dark':'light'):v;document.documentElement.dataset.theme=t;};
 const savePref=async(k:string,v:any)=>{
   const n={...prefs,[k]:v};setPrefs(n);write('kino_settings',n);
   if(k==='theme')applyTheme(v);
   if(k==='language'){document.documentElement.lang=v;setTimeout(()=>window.location.reload(),0);}
   if(k==='notifications' && v && 'Notification' in window){
     try{const perm=Notification.permission==='granted'?'granted':await Notification.requestPermission();if(perm==='granted')new Notification('Kino AI Studio',{body:tr('notificationsOn')});}catch{}
   }
   window.dispatchEvent(new CustomEvent('kino-settings-change',{detail:{[k]:k==='theme'?((v==='system')?(window.matchMedia?.('(prefers-color-scheme: dark)').matches?'dark':'light'):v):v}}));
 };
 const changePassword=async()=>{
   if(newPassword.length<6){setNotice(tr('passwordLength'));return}
   const u=session?.user||session;
   if(sb&&u?.id){
     const r=await sb.auth.updateUser({password:newPassword});
     if(r.error){setNotice(r.error.message);return}
   }else{
     const users=read('kino_local_users',[]);const email=u?.email||session?.email;const user=users.find((x:any)=>x.email===email);
     if(!user||user.password!==currentPassword){setNotice(tr('wrongPassword'));return}
     write('kino_local_users',users.map((x:any)=>x.email===email?{...x,password:newPassword}:x));
   }
   setCurrentPassword('');setNewPassword('');setSecurityOpen(false);setNotice(tr('passwordChanged'));
 };
 return <div className="page">
   <div className="head"><div><div className="eyebrow">{tr('account')}</div><h2>{tr('settingsTitle')}</h2></div></div>
   <section className="panel settingsGrid">
    <div><UserCircle/><h3>{tr('profile')}</h3><p>{session?.user?.user_metadata?.full_name||session?.user?.email||session?.email}</p><button className="ghost" onClick={()=>go('profile')}>{tr('profileManage')}</button></div>
    <div><Globe/><h3>{tr('language')}</h3><select value={prefs.language} onChange={e=>savePref('language',e.target.value)}><option value="uz">O‘zbekcha</option><option value="en">English</option><option value="ru">Русский</option></select></div>
    <div><Bell/><h3>{tr('notifications')}</h3><label className="switch"><input type="checkbox" checked={prefs.notifications} onChange={e=>savePref('notifications',e.target.checked)}/><span>{tr('notificationsOn')}</span></label>{'Notification' in window&&<small className="settingStatus">{Notification.permission==='granted'?'✓ Browser bildirishnomalari ruxsat etilgan':Notification.permission==='denied'?'✕ Browser bildirishnomalari bloklangan':''}</small>}</div>
    <div><Palette/><h3>{tr('appearance')}</h3><select value={prefs.theme} onChange={e=>savePref('theme',e.target.value)}><option value="light">{tr('light')}</option><option value="dark">{tr('dark')}</option><option value="system">{tr('system')}</option></select></div>
    <div><Lock/><h3>{tr('security')}</h3><p>{tr('securityText')}</p><button className="ghost" onClick={()=>{setSecurityOpen(true);setNotice('')}}>{tr('securityManage')}</button></div>
    <div><Volume2/><h3>{tr('aiVoice')}</h3><p>{tr('aiVoiceText')}</p><select value={prefs.aiVoice||'neutral'} onChange={e=>savePref('aiVoice',e.target.value)}><option value="neutral">{tr('neutral')}</option><option value="warm">{tr('warm')}</option><option value="cinematic">{tr('cinematic')}</option></select></div>
   </section>
   <section className="panel" style={{marginTop:14}}><h3>{tr('accountSection')}</h3><p>{session?.user?.email||session?.email}</p><button className="primary" onClick={logout}>{tr('logout')}</button>{notice&&<div className="notice">{notice}</div>}</section>
   {securityOpen&&<div className="apiModal"><section className="panel securityModal"><Lock/><h3>{tr('changePassword')}</h3>{!(sb&&(session?.user||session)?.id)&&<><label>{tr('currentPassword')}</label><input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></>}<label>{tr('newPassword')}</label><input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="••••••••"/><div className="securityActions"><button className="ghost" onClick={()=>setSecurityOpen(false)}>{tr('cancel')}</button><button className="primary" onClick={changePassword}>{tr('save')}</button></div>{notice&&<div className="notice">{notice}</div>}</section></div>}
 </div>
}
function Admin({compact=false}:any){const[payments,setPayments]=useState<Payment[]>(()=>read('kino_payments',[]));useEffect(()=>{(async()=>{if(sb){const{data}=await sb.from('studio_ad_payment_requests').select('*').order('created_at',{ascending:false});if(data)setPayments(data.map((p:any)=>({id:p.id,email:p.user_email,kind:p.kind,amount:p.amount_text||'',status:p.status,receiptName:p.receipt_name||'',createdAt:p.created_at})))}})()},[]);const act=async(id:string,ok:boolean)=>{const next=payments.map(p=>p.id===id?{...p,status:ok?'approved':'rejected'}:p);setPayments(next);write('kino_payments',next);const p=next.find(x=>x.id===id);if(sb&&p){await sb.from('studio_ad_payment_requests').update({status:p.status,reviewed_at:new Date().toISOString()}).eq('id',id)}};return <section className="panel adminPanel"><div className="head"><div><div className="eyebrow">ADMIN</div><h3>To‘lovlarni tasdiqlash</h3></div><span className="status">/admin</span></div>{payments.length===0?<p>Hozircha reklama/hamkorlik to‘lovi so‘rovi yo‘q.</p>:payments.map(p=><div className="shot" key={p.id}><CreditCard/><div><b>{p.email}</b><small>{p.kind} · {p.createdAt}</small><small>Chek: {p.receiptName}</small></div>{p.status==='pending'?<><button className="ghost" onClick={()=>act(p.id,true)}><Check/> Tasdiqlash</button><button className="ghost" onClick={()=>act(p.id,false)}><XCircle/> Rad etish</button></>:<i>{p.status}</i>}</div>)}</section>}
createRoot(document.getElementById('root')!).render(<App/>);
