import React,{useEffect,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{createClient,Session}from'@supabase/supabase-js';
import*as THREE from'three';
import{Film,Clapperboard,Sparkles,Users,FolderKanban,Box,Camera,Lightbulb,Settings,UserCircle,Shield,KeyRound,Plus,Play,Save,Menu,X,ChevronRight,CheckCircle2,Clock3,Layers3,Wand2,LogOut,Move3d,SunMedium,Wind,ScanFace,Footprints,Database,Code2,Upload,Eye,Shirt,Palette,Globe2,MessageSquare,Handshake,Bot,Server,Image as ImageIcon,RefreshCw}from'lucide-react';
import'./styles.css';
import {Professional3DPreview} from './engine3d/Professional3DPreview';

const URL=import.meta.env.VITE_SUPABASE_URL||'',KEY=import.meta.env.VITE_SUPABASE_ANON_KEY||'',sb=URL&&KEY?createClient(URL,KEY):null;
const uid=()=>crypto.randomUUID();
type Character={id:string,name:string,role:string,height:number,skin:string,hair:string,cloth:string,accent:string,face:string};
type Shot={id:string,title:string,duration:number,camera:string,lighting:string,environment:string,action:string,characterIds:string[]};
type Project={id:string,title:string,style:string,status:string,characters:Character[],shots:Shot[],createdAt:string,ownerName?:string,ownerEmail?:string,coverUrl?:string};
const C={skin:'#b97852',hair:'#17191f',cloth:'#26334b',accent:'#d98d4d'};
const newChar=():Character=>({id:uid(),name:'Astra',role:'Bosh qahramon',height:1.72,skin:C.skin,hair:C.hair,cloth:C.cloth,accent:C.accent,face:'heroic'});
const starter=():Project=>{const c=newChar();return{id:uid(),title:'Yangi Cinematic Film',style:'Photorealistic Cinematic',status:'draft',characters:[c],shots:[{id:uid(),title:'01 — Establishing',duration:6,camera:'24mm · crane-up · wide',lighting:'Moon · practicals · volumetric',environment:'Cinematic city · fog · rain',action:'Natural walking and environment motion',characterIds:[c.id]},{id:uid(),title:'02 — Close-up',duration:5,camera:'85mm · slow orbit · DOF',lighting:'Soft key · eye catchlight · rim',environment:'Night street · bokeh',action:'Blink, breathing, subtle emotion',characterIds:[c.id]}],createdAt:new Date().toISOString()}};

function App(){
 const[page,setPage]=useState('home'),[open,setOpen]=useState(false),[session,setSession]=useState<Session|null>(null),[project,setProject]=useState<Project>(starter()),[script,setScript]=useState(''),[saved,setSaved]=useState(false),[authMode,setAuthMode]=useState<'login'|'signup'>('login'),[email,setEmail]=useState(''),[pass,setPass]=useState(''),[msg,setMsg]=useState(''),[isAdmin,setIsAdmin]=useState(false),[projects,setProjects]=useState<Project[]>([]);
 useEffect(()=>{if(!sb)return;sb.auth.getSession().then(({data})=>setSession(data.session));const sub=sb.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>sub.data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!sb||!session)return;loadCloud();checkAdmin()},[session]);
 async function checkAdmin(){if(!sb||!session)return;const{data}=await sb.from('studio_admins').select('admin_email,admin_active').eq('admin_email',(session.user.email||'').toLowerCase()).eq('admin_active',true).maybeSingle();setIsAdmin(!!data)}
 async function loadCloud(){if(!sb||!session)return;const{data}=await sb.from('studio_projects').select('*').eq('studio_owner_id',session.user.id).order('studio_created_at',{ascending:false});if(data?.length)setProjects(data.map((p:any)=>({...starter(),id:p.studio_project_id,title:p.studio_name,style:p.studio_ratio||'Photorealistic Cinematic',status:p.studio_status,createdAt:p.studio_created_at,ownerName:p.studio_owner_name,ownerEmail:p.studio_owner_email})));}
 async function save(){if(!session){setPage('profile');setMsg('Avval ro‘yxatdan o‘ting yoki kiring.');return}if(!sb){setMsg('Supabase ulanmagan.');return}const p={studio_project_id:project.id,studio_owner_id:session.user.id,studio_name:project.title,studio_description:'',studio_status:project.status,studio_ratio:project.style,studio_duration_seconds:project.shots.reduce((a,s)=>a+s.duration,0),studio_created_at:project.createdAt,studio_updated_at:new Date().toISOString(),studio_public:true,studio_owner_name:session.user.user_metadata?.full_name||session.user.email,studio_owner_email:session.user.email};const{error}=await sb.from('studio_projects').upsert(p);if(!error){setSaved(true);setTimeout(()=>setSaved(false),1200);loadCloud()}else setMsg(error.message)}
 async function auth(){if(!sb){setMsg('Supabase ulanmagan. .env ga VITE_SUPABASE_URL va VITE_SUPABASE_ANON_KEY kiriting.');return}const r=authMode==='login'?await sb.auth.signInWithPassword({email,password:pass}):await sb.auth.signUp({email,password:pass,options:{data:{full_name:email.split('@')[0]}}});setMsg(r.error?.message|| (authMode==='signup'?'Email tasdiqlash xabari yuborildi.':'Kirish muvaffaqiyatli.'))}
 const nav:any[]=[['home','Bosh sahifa',Clapperboard],['create','Kino yaratish',Film],['script','AI ssenariy',Sparkles],['characters','Personajlar',Users],['studio','Cinema Engine',Box],['projects','Loyihalar',FolderKanban],['movies','Mening kinolarim',Globe2],['integrations','Bot / API ulash',Bot],['collab','Hamkorlik',Handshake],['partners','Hamkorlar / Reklama',ImageIcon],['profile','Profil',UserCircle],['settings','Sozlamalar',Settings],...(isAdmin?[['admin','Admin Studio',Shield]]:[])];
 return <div className="app"><aside className={'side '+(open?'open':'')}><div className="brand"><div className="logo"><Film/></div><b>KINO AI<small>STUDIO · PRIVATE 3D CORE</small></b><button className="icon mobileX" onClick={()=>setOpen(false)}><X/></button></div><div className="label">WORKSPACE</div>{nav.map(([n,t,I])=><button key={n} className={'nav '+(page===n?'sel':'')} onClick={()=>{if(['create','script','characters','studio','projects'].includes(n)&&!session){setPage('profile');setMsg('Bu bo‘lim uchun akkauntga kirish kerak.')}else{setPage(n);setOpen(false)}}}><I size={18}/><span>{t}</span>{page===n&&<ChevronRight size={14}/>}</button>)}<div className="bottom"><div className="online"><i/>PRIVATE ENGINE<small>Own procedural 3D asset core</small></div>{session&&<button className="nav" onClick={()=>sb?.auth.signOut()}><LogOut size={18}/><span>Chiqish</span></button>}</div></aside><main><header><button className="icon menu" onClick={()=>setOpen(true)}><Menu/></button><span>KINO AI STUDIO / {nav.find(x=>x[0]===page)?.[1]}</span><div>{session?<em>● Cloud online</em>:<button className="ghost" onClick={()=>setPage('profile')}>Kirish</button>}<button className="primary sm" onClick={()=>session?setPage('create'):setPage('profile')}><Plus size={15}/> Yangi kino</button></div></header>{page==='home'&&<Home go={setPage} project={project}/>} {page==='create'&&<Create project={project} setProject={setProject} script={script} setScript={setScript} save={save}/>} {page==='script'&&<Script script={script} setScript={setScript} project={project} setProject={setProject}/>} {page==='characters'&&<Characters project={project} setProject={setProject}/>} {page==='studio'&&<Studio project={project}/>} {page==='projects'&&<Projects projects={projects} project={project} setProject={setProject} go={setPage}/>} {page==='movies'&&<Movies projects={projects}/>} {page==='integrations'&&<Integrations/>} {page==='collab'&&<SimplePage icon={<Handshake/>} title="Hamkorlik" text="Loyihaga hamkor qo‘shish, rollar va umumiy ishlab chiqish uchun tayyor platforma bo‘limi."/>} {page==='partners'&&<SimplePage icon={<ImageIcon/>} title="Hamkorlar / Reklama" text="Film ichidagi reklama, homiylik va hamkor takliflarini boshqarish bo‘limi."/>} {page==='profile'&&<Profile session={session} mode={authMode} setMode={setAuthMode} email={email} setEmail={setEmail} pass={pass} setPass={setPass} msg={msg} auth={auth}/>} {page==='settings'&&<SettingsPage/>} {page==='admin'&&isAdmin&&<Admin/>}</main></div>
}

function Home({go,project}:any){return <div className="page"><section className="hero"><div className="heroText"><div className="eyebrow">● PRIVATE CINEMA ENGINE · OWN 3D CORE</div><h1>G‘oyangizni<br/><span>kinoga aylantiring.</span></h1><p>Script → Scene Graph → Character Identity → Motion → Camera → Lighting → Environment → Timeline → Render.</p><button className="primary" onClick={()=>go('create')}><Play size={17}/> Kino yaratishni boshlash</button><button className="ghost" onClick={()=>go('studio')}><Box size={17}/> O‘zimizning 3D Engine</button></div><div className="reel"><Move3d size={64}/><b>OWN<br/>3D CORE</b></div></section><div className="head"><div><div className="eyebrow">WORKSPACE</div><h2>Studio paneli</h2></div><small>{project.shots.length} shots · {project.characters.length} characters</small></div><div className="cards">{[[Film,'Kino yaratish','Ssenariyni scene va shot pipeline ga aylantirish','create'],[Sparkles,'AI ssenariy','OpenRouter ulanishiga tayyor AI layer','script'],[Users,'Personajlar','O‘zimizning procedural 3D character core','characters'],[Box,'Cinema Engine','Noldan qurilgan scene, camera, light va motion core','studio'],[Globe2,'Mening kinolarim','Yaratilgan kinolar va ularning mualliflarini ko‘rish','movies'],[Bot,'Bot / API','Telegram bot va universal API bridge','integrations']].map(([I,t,d,p]:any)=><button className="card" key={t} onClick={()=>go(p)}><I/><b>{t}</b><p>{d}</p><ChevronRight/></button>)}</div><div className="stats"><div><b>{project.shots.length}</b><small>SHOTS</small></div><div><b>{project.shots.reduce((a,s)=>a+s.duration,0)}s</b><small>TIMELINE</small></div><div><b>{project.characters.length}</b><small>CHARACTERS</small></div><div><b>OWN</b><small>3D CORE</small></div></div></div>}

function Create({project,setProject,script,setScript,save}:any){return <div className="page"><div className="head"><div><div className="eyebrow">FILM BUILDER</div><h2>Kino yaratish</h2></div><button className="ghost" onClick={save}><Save size={15}/>Saqlash</button></div><div className="grid"><section className="panel"><label>LOYIHA NOMI</label><input value={project.title} onChange={e=>setProject({...project,title:e.target.value})}/><label>SSENARIY</label><textarea value={script} onChange={e=>setScript(e.target.value)} placeholder="Film voqeasini yozing..."/><div className="row"><button className="ghost" onClick={()=>{setScript(script||'Yomg‘irli tungi shaharda qahramon kelajakdagi sirni izlaydi.');setProject({...project,status:'analyzed'})}}><Wand2/> Scene Analyze</button><button className="ghost" onClick={save}><Database/> Supabase Cloud</button></div><label>VIZUAL USLUB</label><select value={project.style} onChange={e=>setProject({...project,style:e.target.value})}><option>Photorealistic Cinematic</option><option>Dark Cinematic</option><option>Cyberpunk Cinematic</option><option>Epic Fantasy</option><option>Stylized 3D Film</option></select><div className="pipeline"><span>1 SCRIPT</span><i>→</i><span>2 SCENE</span><i>→</i><span>3 SHOT</span><i>→</i><span>4 OWN 3D</span><i>→</i><span>5 RENDER</span></div></section><section className="panel"><div className="pt">SHOT TIMELINE <button className="icon" onClick={()=>setProject({...project,shots:[...project.shots,{id:uid(),title:`${String(project.shots.length+1).padStart(2,'0')} — New Shot`,duration:5,camera:'35mm · tracking',lighting:'Key + rim',environment:'',action:'',characterIds:project.characters.slice(0,1).map((c:any)=>c.id)}]})}><Plus size={15}/></button></div>{project.shots.map((s:Shot,i:number)=><div className="shot" key={s.id}><span>{String(i+1).padStart(2,'0')}</span><div><b>{s.title}</b><small>{s.camera} · {s.duration}s</small></div><i>SCENE READY</i></div>)}<div className="notice"><b>RENDER MODEL STATUS</b><br/>AI video model hali ulanmagan. Engine real model mavjud bo‘lmasa fake MP4 yaratmaydi. Ichki 3D core esa mustaqil ishlaydi.</div></section></div></div>}

function Script({script,setScript,project,setProject}:any){return <div className="page"><div className="head"><div><div className="eyebrow">AI WRITER</div><h2>AI ssenariy</h2></div><span className="status">OpenRouter adapter · ready</span></div><section className="panel"><label>SSENARIY G‘OYASI</label><textarea className="bigText" value={script} onChange={e=>setScript(e.target.value)} placeholder="Masalan: 2035-yilda Toshkentda sirli signal topgan yosh muhandis..."/><div className="row"><button className="primary" onClick={()=>{setScript(script||'Kirish sahnasi: tungi shaharda sirli signal topiladi. Qahramon signal manbasini izlab yo‘lga chiqadi.');setProject({...project,status:'script_ready'})}}><Sparkles/> Ssenariyni tayyorlash</button><button className="ghost" onClick={()=>setScript('')}>Tozalash</button></div><div className="roadmap"><h3>AI PIPELINE</h3><div className="road">G‘oya → struktura → personajlar → sahnalar → shotlar → dialog/emotion → kamera → 3D scene plan</div></div></section></div>}

function Characters({project,setProject}:any){const[c,setC]=useState(project.characters[0]);useEffect(()=>setC(project.characters[0]),[project.characters]);return <div className="page"><div className="head"><div><div className="eyebrow">CHARACTER LAB</div><h2>Personajlar</h2></div><button className="primary" onClick={()=>{const n=newChar();setProject({...project,characters:[...project.characters,n]});setC(n)}}><Plus/> Personaj</button></div><div className="charLayout"><section className="panel charList">{project.characters.map((x:any)=><button className={'charRow '+(c?.id===x.id?'active':'')} onClick={()=>setC(x)} key={x.id}><span className="miniHead" style={{background:x.accent}}><ScanFace/></span><div><b>{x.name}</b><small>{x.role}</small></div><ChevronRight/></button>)}</section><section className="panel"><div className="editorTop"><div><div className="eyebrow">IDENTITY LOCK</div><h3>{c?.name}</h3></div><span className="lock">CONTINUITY LOCK</span></div>{c&&<><div className="characterStage"><div className="charPreview"><OwnCharacter character={c}/></div><div className="assetInfo"><div className="assetTag"><ScanFace/> Face identity</div><div className="assetTag"><Shirt/> Outfit identity</div><div className="assetTag"><Footprints/> Motion rig</div><div className="assetTag"><Wind/> Hair/cloth motion</div></div></div><div className="formGrid"><label>ISM<input value={c.name} onChange={e=>{const n={...c,name:e.target.value};setC(n);setProject({...project,characters:project.characters.map((x:any)=>x.id===c.id?n:x)})}}/></label><label>ROL<select value={c.role} onChange={e=>{const n={...c,role:e.target.value};setC(n);setProject({...project,characters:project.characters.map((x:any)=>x.id===c.id?n:x)})}}><option>Bosh qahramon</option><option>Ikkinchi qahramon</option><option>Antagonist</option><option>Background</option></select></label><label>BO‘Y<input type="number" step="0.01" value={c.height} onChange={e=>{const n={...c,height:+e.target.value};setC(n);setProject({...project,characters:project.characters.map((x:any)=>x.id===c.id?n:x)})}}/></label><label>KIYIM<input value={c.cloth} onChange={e=>{const n={...c,cloth:e.target.value};setC(n);setProject({...project,characters:project.characters.map((x:any)=>x.id===c.id?n:x)})}}/></label></div></>}</section></div></div>}

function OwnCharacter({character}:any){return <Professional3DPreview character={character}/>;}

function Studio({project}:any){return <div className="page"><div className="head"><div><div className="eyebrow">PRIVATE 3D ENGINE</div><h2>Cinema Engine</h2></div><span className="status">PROFESSIONAL PROCEDURAL CORE</span></div><div className="engine"><section className="panel viewport"><Professional3DPreview large character={project.characters[0]}/><div className="hud">SCENE 01 · {project.style}<small> · procedural character / rig / IK-ready / camera / cinematic light</small></div><div className="engineBadge"><Move3d size={14}/> <span>OWN PROCEDURAL 3D CORE</span></div></section><section className="panel"><div className="pt">ENGINE MODULES</div><div className="modules">{[[Layers3,'Scene Graph','production hierarchy'],[Users,'Character Identity','parametric character'],[ScanFace,'Face System','eyes · brows · mouth'],[Footprints,'Skeleton / IK','humanoid rig'],[Wind,'Motion','procedural animation'],[Camera,'Camera','lens + cinematic motion'],[SunMedium,'Lighting','key · fill · rim'],[RefreshCw,'Timeline','shot sequencing'],[Server,'Render Gate','real worker only'],[Code2,'Adapters','AI optional']].map(([I,t,d]:any)=><div className="mod" key={t}><I/><b>{t}</b><small>{d}</small></div>)}</div><div className="notice"><b>3D CORE:</b> Character va environment geometry kod orqali procedural generatsiya qilinadi. Tayyor character asset import qilinmaydi. Render natijasi faqat haqiqiy render worker mavjud bo‘lganda “tayyor” deb belgilanadi.</div></section></div></div>}

function Projects({projects,project,setProject,go}:any){return <div className="page"><div className="head"><div><div className="eyebrow">CLOUD PROJECTS</div><h2>Loyihalar</h2></div><button className="primary" onClick={()=>{setProject(starter());go('create')}}><Plus/> Yangi</button></div>{projects.length===0?<section className="panel"><b>Hali cloud loyiha yo‘q.</b><p>Akkauntga kirib loyiha saqlang.</p></section>:projects.map((p:any)=><section className="panel project" key={p.id}><div className="thumb"><Film/></div><div><b>{p.title}</b><p>{p.style} · {p.status}</p><small>Muallif: {p.ownerName||p.ownerEmail||'Noma’lum'}</small></div><button className="ghost" onClick={()=>{setProject(p);go('create')}}>Ochish</button></section>)}</div>}
function Movies({projects}:any){return <div className="page"><div className="head"><div><div className="eyebrow">PUBLIC CINEMA</div><h2>Mening kinolarim</h2></div><small>Mualliflar ko‘rinadi</small></div>{projects.length===0?<section className="panel"><b>Kinolar hali chiqarilmagan.</b><p>Saqlangan va public qilingan filmlar shu yerda muallifi bilan ko‘rinadi.</p></section>:<div className="movieGrid">{projects.map((p:any)=><article className="movieCard" key={p.id}><div className="movieCover"><Film/></div><h3>{p.title}</h3><p>{p.style}</p><small>🎬 Muallif: <b>{p.ownerName||p.ownerEmail||'Noma’lum'}</b></small><button className="ghost"><Eye/> Ko‘rish</button></article>)}</div>}</div>}
function Integrations(){return <div className="page"><div className="head"><div><div className="eyebrow">CONNECTORS</div><h2>Bot / Universal API</h2></div></div><div className="cards">{[[Bot,'Telegram Bot','Bot ssenariy, buyruq va job statuslarini API orqali yuboradi.'],[Code2,'Universal API','Boshqa botlar ham loyiha yaratishi va job yuborishi mumkin.'],[Sparkles,'OpenRouter','AI ssenariy adapteri. Kalit backend/secret muhitda saqlanadi.'],[Server,'Render Worker','GPU/AI renderer mavjud bo‘lmasa job MODEL_UNAVAILABLE bilan to‘xtaydi.']].map(([I,t,d]:any)=><div className="card" key={t}><I/><b>{t}</b><p>{d}</p></div>)}</div><section className="panel"><label>BOT FLOW</label><div className="pipeline"><span>TELEGRAM</span><i>→</i><span>UNIVERSAL API</span><i>→</i><span>SUPABASE JOB</span><i>→</i><span>OWN 3D / AI ADAPTER</span><i>→</i><span>TELEGRAM DELIVERY</span></div></section></div>}
function Admin(){return <div className="page"><div className="head"><div><div className="eyebrow">OWNER CONTROL PLANE</div><h2>Admin Studio</h2></div><span className="status">ADMIN ACTIVE</span></div><div className="cards"><div className="card"><Shield/><b>Owner</b><p>Admin roli Supabase'dagi studio_admins jadvali orqali server-side nazorat qilinadi.</p></div><div className="card"><KeyRound/><b>API Keys</b><p>Universal API client kalitlari backendda boshqariladi; secret kalit APK ichiga yozilmaydi.</p></div><div className="card"><Sparkles/><b>AI Rules</b><p>AI ssenariy qoidalari, model adapterlari va prompt konfiguratsiyasi shu boshqaruv qatlamiga ulanadi.</p></div><div className="card"><Database/><b>Audit</b><p>Admin amallari audit log orqali qayd qilinadigan arxitektura.</p></div></div></div>}
function Profile({session,mode,setMode,email,setEmail,pass,setPass,msg,auth}:any){return <div className="page">{session?<section className="profile"><UserCircle/><div className="eyebrow">AUTHENTICATED</div><h2>Profil</h2><p>{session.user.email}</p><div className="continuity">Cloud session faol. Loyiha va kinolar Supabase orqali akkauntga bog‘lanadi.</div></section>:<div className="auth"><div><div className="eyebrow">KINO AI STUDIO</div><h2>Avval akkaunt yarating.</h2><p>Kino yaratish, personajlar, Cinema Engine, loyihalar va cloud ma’lumotlar faqat ro‘yxatdan o‘tgan foydalanuvchiga ochiladi.</p></div><section className="panel authbox"><label>EMAIL</label><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@example.com"/><label>PAROL</label><input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="••••••••"/><button className="primary full" onClick={auth}>{mode==='login'?'Kirish':'Ro‘yxatdan o‘tish'}</button>{msg&&<div className="notice">{msg}</div>}<button className="text" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Yangi akkaunt yaratish':'Akkauntim bor — kirish'}</button></section></div>}</div>}
function SettingsPage(){return <div className="page"><div className="head"><div><div className="eyebrow">STUDIO SETTINGS</div><h2>Sozlamalar</h2></div></div><div className="settings">{[[Palette,'Visual Style','White UI + dark text + orange accent'],[Move3d,'3D Core','Procedural assets, camera, light and motion'],[Database,'Storage','Supabase database + storage'],[Shield,'Security','RLS + server-side admin'],[Sparkles,'AI','OpenRouter adapter'],[Bot,'Telegram','Universal API bridge']].map(([I,t,d]:any)=><section className="panel set" key={t}><I/><div><b>{t}</b><p>{d}</p></div></section>)}</div></div>}
function SimplePage({icon,title,text}:any){return <div className="page"><section className="panel profile">{icon}<h2>{title}</h2><p>{text}</p></section></div>}

createRoot(document.getElementById('root')!).render(<App/>);
